### ISSUE TITLE
可以增加暗黑模式吗？

### ISSUE THREAD

**Issue by chenjiakuan** [zpr1g/ant-design-pro-plus#6]
老板  可以把暗黑模式增加进来吗？

**Comment by zpr1g** [comment]
如果只是使用暗黑模式的话，可以看看这个 [issue](https://github.com/ant-design/ant-design/issues/23237#issuecomment-613290095) 。现在因为标签页功能还无法升级到 umi 3.x ，后续如果可以升级的话，我会第一时间升级的，届时配置 antd 也会很方便了。
