### ISSUE TITLE
点击菜单 没反应

### ISSUE THREAD

**Issue by chenjiakuan** [zpr1g/ant-design-pro-plus#7]
yarn install 安装依赖。  运行 点击菜单 没反应。 
![image](https://user-images.githubusercontent.com/18523983/83712276-f3bf7d80-a657-11ea-8285-e9f8818c33cc.png)

**Comment by zpr1g** [comment]
pro-layout 炸了... https://github.com/ant-design/ant-design-pro-layout/issues/489

临时的解决方案：先删除 node_modules ，然后锁死 `"@ant-design/pro-layout": "5.0.8"`，就可用了。

**Comment by ZidiHu** [comment]
> pro-layout 炸了... [ant-design/ant-design-pro-layout#489](https://github.com/ant-design/ant-design-pro-layout/issues/489)
> 
> 临时的解决方案：先删除 node_modules ，然后锁死 `"@ant-design/pro-layout": "5.0.8"`，就可用了。

  请问锁死`"@ant-design/pro-layout": "5.0.8"`是咋整呀？我删除了node_modules然后把package.json里@ant-design/pro-layout改成5.0.8还是不能点击

**Comment by zpr1g** [comment]
@ZidiHu 不应该啊，我本地试过的，改成 `"@ant-design/pro-layout": "5.0.8"` ，删除 node_modules 再重装就行了啊。再说 pro-layout 这个 bug 还没发版修复吗 \_(:3J∠)\_

**Comment by ZidiHu** [comment]
> @ZidiHu 不应该啊，我本地试过的，改成 `"@ant-design/pro-layout": "5.0.8"` ，删除 node_modules 再重装就行了啊。再说 pro-layout 这个 bug 还没发版修复吗 _(:3J∠)_

谢谢好心人！请问你说的重装是npm install吗 我删掉node_modules然后跑npm install还是一样

**Comment by zpr1g** [comment]
@ZidiHu 我是用的 cnpm ，不过应该没啥影响吧，要不然试试删除 node_modules 再 `npm cache clean --force` 清除缓存，最后安装依赖看看 🤔

**Comment by ZidiHu** [comment]
> @ZidiHu 我是用的 cnpm ，不过应该没啥影响吧，要不然试试删除 node_modules 再 `npm cache clean --force` 清除缓存，最后安装依赖看看 🤔

多谢多谢！
