### ISSUE TITLE
logout error

### ISSUE THREAD

**Issue by qq919623547** [zpr1g/ant-design-pro-plus#9]
在执行退出登录时会有Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

**Comment by zpr1g** [comment]
我特地试了一下，如果删除重装依赖是有这个警告，但是我本地之前 antd 版本还是 4.3.4 的时候是没有这个警告的，感觉是 antd 的问题 :joy:

**Comment by qq919623547** [comment]
在 BasicLayout.tsx 里 将  
useEffect(() => {
    setTimeout(() => {
      setMenuLoading(false);
    }, 2000);
    return ()=>setMenuLoading(false);
  }, []);
去掉 useEffect
只用setTimeout(() => {
    setMenuLoading(false);
  }, 2000);
报错解除，目前还没看到别的影响，大佬如果有新的解决方法可以update一下呀。

**Comment by zpr1g** [comment]
首先我的源码里边没有 `return ()=>setMenuLoading(false)` ，其次，这个和报错位置八竿子打不着关系，再者我也试过了把整个 useEffect 去掉仍然存在这个问题。不知道你这个解决了是什么操作，有时间我再深入看看吧。
